spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true

server:
  port: 8080

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expire-seconds:
    access-token: 3600
    refresh-token: 604800
  header:
    access-token: Authorization
    refresh-token: Authorization-refresh
